# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana-nginx
  labels:
    id: {{ .Release.Name }}-deployment-grafana-nginx
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/grafana/grafana-nginx.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.grafanaNginx | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-grafana-nginx
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-grafana-nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/grafana/grafana-nginx.configmap.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: {{ .Release.Name }}-grafana-nginx
          configMap:
            name: {{ .Release.Name }}-grafana-nginx
      {{- include "capellacollab.pod.spec" . | indent 6 -}}
      containers:
        - name: {{ .Release.Name }}-grafana-nginx
          {{- include "capellacollab.container.spec" . | indent 10 -}}
          {{ if .Values.docker.images.nginxUnprivileged }}
          image: {{ .Values.docker.images.nginxUnprivileged }}
          {{ else }}
          image: {{ .Values.docker.registry.external }}/nginxinc/nginx-unprivileged
          {{ end }}
          ports:
            - name: grafui
              containerPort: 3118
              protocol: TCP
          resources:
            requests:
              cpu: "1m"
              memory: 5Mi
              ephemeral-storage: "1Gi"
            limits:
              cpu: "25m"
              memory: 20Mi
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: {{ .Release.Name }}-grafana-nginx
              mountPath: /etc/nginx
{{ end }}
