# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana-server
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-deployment-grafana-server
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/grafana" "/grafana.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.grafana | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-grafana-server
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-grafana-server
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/grafana" "/grafana.configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-grafana
      containers:
        - name: grafana
          image: {{ .Values.docker.registry.external -}}{{- .Values.docker.images.grafana }}
          ports:
            - containerPort: 3000
          resources:
            {{ if eq .Values.target "local" }}
            limits:
              cpu: "0.1"
              memory: 50Mi
            requests:
              cpu: "0.05"
              memory: 5Mi
            {{ else }}
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
            {{ end }}
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: storage
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-grafana
            items:
              - key: grafana.ini
                path: grafana.ini
        - name: datasources
          configMap:
            name: {{ .Release.Name }}-grafana
            items:
              - key: datasources.yaml
                path: datasources.yaml
        - name: dashboards
          configMap:
            name: {{ .Release.Name }}-grafana
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name -}}-grafana
