# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-alerting
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-grafana-alerting
data:
{{ (.Files.Glob "config/grafana/alerting/*.yaml").AsConfig | indent 2 }}
{{ end }}
