# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana-nginx
  labels:
    id: {{ .Release.Name }}-grafana-nginx-service
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-grafana-nginx
  ports:
    - port: 3118
      targetPort: grafui
      protocol: TCP
      name: grafui
