# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-grafana-nginx
data:
  nginx.conf: |-
    {{ tpl (.Files.Get "config/nginx-grafana.conf") . | nindent 4 }}
{{ end }}
