# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana-nginx
  labels:
    id: {{ .Release.Name }}-deployment-grafana-nginx
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/grafana/nginx.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.grafanaNginx | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-grafana-nginx
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-grafana-nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/grafana/nginx.configmap.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: {{ .Release.Name }}-grafana-nginx
          configMap:
            name: {{ .Release.Name }}-grafana-nginx
      {{- include "capellacollab.pod.spec" . | indent 6 -}}
      containers:
        - name: {{ .Release.Name }}-grafana-nginx
          {{- include "capellacollab.container.spec" . | indent 10 -}}
          {{ if .Values.docker.images.nginxUnprivileged }}
          image: {{ .Values.docker.images.nginxUnprivileged }}
          {{ else }}
          image: {{ .Values.docker.registry.external }}/nginxinc/nginx-unprivileged
          {{ end }}
          ports:
            - name: grafui
              containerPort: 3118
              protocol: TCP
          resources:
            {{ if .Values.development }}
            limits:
              cpu: "0.1"
              memory: 50Mi
              ephemeral-storage: "2Gi"
            requests:
              cpu: "0.05"
              memory: 5Mi
            {{ else }}
            limits:
              cpu: "1"
              memory: 100Mi
              ephemeral-storage: "2Gi"
            requests:
              cpu: "0.25"
              memory: 50Mi
            {{ end }}
          volumeMounts:
            - name: {{ .Release.Name }}-grafana-nginx
              mountPath: /etc/nginx
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
{{ end }}
