apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guacamole-postgres
  labels: 
    id: {{ .Release.Name }}-service-guacamole-postgres
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-guacamole-postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
