# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-session-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-session-nginx
data:
  nginx.conf: |-
    pid /tmp/nginx.pid;

    events{}
    http {
        # These options are needed to run as non-root
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        server {
            listen 8080 default_server;
            server_name _;

            root /usr/share/nginx/html;
            error_page 502 /502.html;
            error_page 401 /401.html;

            resolver {{ .Values.cluster.dns.service }}.{{ .Values.cluster.dns.namespace }}.svc.cluster.local;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_buffering off;

            location ~ ^/session/([a-z]+)/(.*)$ {
              set $ccm_session_id $1;
              set $query $2;
              auth_request /auth;
              proxy_pass http://$ccm_session_id.{{ .Values.backend.k8sSessionNamespace }}.svc.cluster.local:80/session/$ccm_session_id/$query$is_args$args;
            }

            location ~ ^/session/([a-z]+) {
              set $ccm_session_id $1;
              auth_request /auth;
              proxy_pass http://$ccm_session_id.{{ .Values.backend.k8sSessionNamespace }}.svc.cluster.local:80/session/$ccm_session_id$is_args$args;
            }

            location /auth {
                proxy_method POST;
                proxy_pass_request_body off;
                proxy_pass_request_headers off;
                proxy_set_header Cookie $http_cookie;
                proxy_pass http://{{ .Release.Name }}-backend.{{ .Release.Namespace }}.svc.cluster.local:80/api/v1/sessions/$ccm_session_id/tokens/validate?token=$cookie_session_token;
            }
        }
    }
  502.html: |-
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
          }
        </style>
      </head>
      <body>
        <h2>Session is not reachable - 502 Bad Gateway</h2>

        <div>Please wait a few seconds and try to reconnect.</div>
        <div>
          If it doesn't work, check the status of the session in the Capella
          Collaboration Manager.
        </div>
        <div>
          If this error is persistent, please contact your system administrator.
        </div>
      </body>
    </html>
  401.html: |-
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
          }
        </style>
      </head>
      <body>
        <h2>Not authenticated against session - 401 Authorization Required</h2>

        <div>
          The error can occur for various reasons:
          <ul>
            <li>The session has been terminated in the Capella Collaboration Manager.</li>
            <li>You've tried to connect to a session directly. You have to connect via the Capella Collaboration Manager.</li>
        </div>
        <div>
          If you think this error shouldn't appear, please contact your system administrator.
        </div>
      </body>
    </html>
