/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



export type AnnouncementLevel = 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'alert';

export const AnnouncementLevel = {
    Primary: 'primary' as AnnouncementLevel,
    Secondary: 'secondary' as AnnouncementLevel,
    Success: 'success' as AnnouncementLevel,
    Danger: 'danger' as AnnouncementLevel,
    Warning: 'warning' as AnnouncementLevel,
    Info: 'info' as AnnouncementLevel,
    Alert: 'alert' as AnnouncementLevel
};

