/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



export interface BetaConfigurationInput { 
    /**
     * Enable beta-testing features. Disabling this will un-enroll all beta-testers.
     */
    enabled?: boolean;
    /**
     * Allow users to register themselves as beta-testers.
     */
    allow_self_enrollment?: boolean;
}

