/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { Role } from './role';
import { BuiltInLinkItem } from './built-in-link-item';


export interface BuiltInNavbarLink { 
    name: string;
    /**
     * Role required to see this link.
     */
    role: Role;
    /**
     * Built-in service to link to.
     */
    service: BuiltInLinkItem;
}
export namespace BuiltInNavbarLink {
}


