/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { Protocol } from './protocol';


export interface CreateT4CInstance { 
    host: string;
    port: number;
    cdo_port: number;
    http_port?: number | null;
    rest_api: string;
    username: string;
    protocol: Protocol;
    name: string;
    version_id: number;
    license_server_id: number;
    is_archived?: boolean | null;
    password: string;
}
export namespace CreateT4CInstance {
}


