/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



export const EventType = {
    CreatedUser: 'CreatedUser',
    AddedToProject: 'AddedToProject',
    RemovedFromProject: 'RemovedFromProject',
    AssignedProjectRoleUser: 'AssignedProjectRoleUser',
    AssignedProjectRoleManager: 'AssignedProjectRoleManager',
    AssignedProjectPermissionReadOnly: 'AssignedProjectPermissionReadOnly',
    AssignedProjectPermissionReadWrite: 'AssignedProjectPermissionReadWrite',
    AssignedRoleAdmin: 'AssignedRoleAdmin',
    AssignedRoleUser: 'AssignedRoleUser',
    UserBlocked: 'UserBlocked',
    UserUnblocked: 'UserUnblocked'
} as const;
export type EventType = typeof EventType[keyof typeof EventType];

