/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



export interface FeedbackProbabilityConfigurationOutput { 
    /**
     * Whether the feedback probability is enabled.
     */
    enabled: boolean;
    /**
     * The percentage of users that will be asked for feedback.
     */
    percentage: number;
}

