/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { UserScopesInput } from './user-scopes-input';
import { AdminScopesInput } from './admin-scopes-input';
import { ProjectUserScopesInput } from './project-user-scopes-input';


export interface FineGrainedResourceInput { 
    user?: UserScopesInput;
    admin?: AdminScopesInput;
    /**
     * Project Slug / Resource mapping.
     */
    projects?: { [key: string]: ProjectUserScopesInput; };
}

