/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { Message } from './message';
import { SimpleT4CRepositoryWithIntegrations } from './simple-t4-c-repository-with-integrations';


export interface PayloadResponseModelListSimpleT4CRepositoryWithIntegrations { 
    warnings: Array<Message> | null;
    errors: Array<Message> | null;
    payload: Array<SimpleT4CRepositoryWithIntegrations>;
}

