/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { SessionType } from './session-type';
import { SessionProvisioningRequest } from './session-provisioning-request';


export interface PostSessionRequest { 
    tool_id: number;
    version_id: number;
    session_type?: SessionType;
    /**
     * The identifier of the connection method to use
     */
    connection_method_id: string;
    provisioning?: Array<SessionProvisioningRequest>;
}
export namespace PostSessionRequest {
}


