/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { ProjectType } from './project-type';
import { UserMetadata } from './user-metadata';
import { ProjectVisibility } from './project-visibility';


export interface Project { 
    id: number;
    name: string;
    slug: string;
    description: string | null;
    visibility: ProjectVisibility;
    type: ProjectType;
    users: UserMetadata;
    is_archived: boolean;
}
export namespace Project {
}


