/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { MemoryResourcesInput } from './memory-resources-input';
import { CPUResourcesInput } from './cpu-resources-input';


export interface ResourcesInput { 
    /**
     * Configuration about the number of CPU cores that sessions can use.
     */
    cpu?: CPUResourcesInput;
    /**
     * Configuration about the amount of memory that sessions can use.
     */
    memory?: MemoryResourcesInput;
}

