/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { LoggingConfigurationInput } from './logging-configuration-input';
import { PrometheusConfigurationInput } from './prometheus-configuration-input';


export interface SessionMonitoringInput { 
    /**
     * Configuration for monitoring and garbage collection.
     */
    prometheus?: PrometheusConfigurationInput;
    /**
     * Configuration for side-car logging container.
     */
    logging?: LoggingConfigurationInput;
}

