/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



/**
 * Information about the connection to the session.
 */
export interface SessionConnectionInformation { 
    /**
     * Configuration for the local storage of the frontend. The provided key/value pairs should be set by the frontend.
     */
    local_storage: { [key: string]: string; };
    t4c_token: string | null;
    redirect_url: string | null;
}

