/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



export type SessionState = 'Running' | 'Failed' | 'Terminated' | 'Pending' | 'NotFound' | 'Unknown';

export const SessionState = {
    Running: 'Running' as SessionState,
    Failed: 'Failed' as SessionState,
    Terminated: 'Terminated' as SessionState,
    Pending: 'Pending' as SessionState,
    NotFound: 'NotFound' as SessionState,
    Unknown: 'Unknown' as SessionState
};

