/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { SimpleLicenseServer } from './simple-license-server';
import { Protocol } from './protocol';
import { SimpleToolVersion } from './simple-tool-version';


export interface T4CInstance { 
    host: string;
    port: number;
    cdo_port: number;
    http_port: number | null;
    rest_api: string;
    username: string;
    protocol: Protocol;
    id: number;
    name: string;
    version: SimpleToolVersion;
    license_server: SimpleLicenseServer;
    is_archived: boolean;
}
export namespace T4CInstance {
}


