/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { ToolSessionConnectionOutput } from './tool-session-connection-output';
import { ResourcesOutput } from './resources-output';
import { SessionMonitoringOutput } from './session-monitoring-output';
import { PersistentWorkspaceSessionConfigurationOutput } from './persistent-workspace-session-configuration-output';
import { Environment1 } from './environment1';
import { ToolModelProvisioningOutput } from './tool-model-provisioning-output';


export interface ToolSessionConfigurationOutput { 
    resources: ResourcesOutput;
    /**
     * Environment variables, which are mounted into session containers. You can use f-strings to reference other environment variables in the value. 
     */
    environment: object;
    connection: ToolSessionConnectionOutput;
    monitoring: SessionMonitoringOutput;
    /**
     * Configuration regarding read-only sessions & automatic session provisioning.
     */
    provisioning: ToolModelProvisioningOutput;
    /**
     * Configuration for persistent workspaces.
     */
    persistent_workspaces: PersistentWorkspaceSessionConfigurationOutput;
}

