/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { EnvironmentValue } from './environment-value';
import { GuacamoleConnectionMethodInput } from './guacamole-connection-method-input';
import { HTTPConnectionMethodInput } from './http-connection-method-input';
import { ToolSessionSharingConfigurationInput } from './tool-session-sharing-configuration-input';
import { HTTPPortsInput } from './http-ports-input';


export interface ToolSessionConnectionInputMethodsInner { 
    id?: string;
    type?: string;
    name?: string;
    description?: string;
    ports?: HTTPPortsInput;
    /**
     * Connection method specific environment variables. Check the global environment field for more information. 
     */
    environment?: { [key: string]: EnvironmentValue; };
    sharing?: ToolSessionSharingConfigurationInput;
    redirect_url?: string;
    /**
     * Cookies, which are required to connect to the session. 
     */
    cookies?: { [key: string]: string; };
}

