/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */

import { SessionPorts } from './session-ports';
import { ToolSessionSharingConfigurationOutput } from './tool-session-sharing-configuration-output';
import { Environment1 } from './environment1';


export interface ToolSessionConnectionMethod { 
    id: string;
    type: string;
    name: string;
    description: string;
    ports: SessionPorts;
    /**
     * Connection method specific environment variables. Check the global environment field for more information. 
     */
    environment: { [key: string]: Environment1; };
    sharing: ToolSessionSharingConfigurationOutput;
}

