/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



export type UserTokenVerb = 'GET' | 'CREATE' | 'UPDATE' | 'DELETE';

export const UserTokenVerb = {
    Get: 'GET' as UserTokenVerb,
    Create: 'CREATE' as UserTokenVerb,
    Update: 'UPDATE' as UserTokenVerb,
    Delete: 'DELETE' as UserTokenVerb
};

