/*
 * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Capella Collaboration Manager API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 + To generate a new version, run `make openapi` in the root directory of this repository.
 */



export interface UserScopesOutput { 
    /**
     * Manage sessions of your own user. With the UPDATE permission a session can be shared with another user and files can be modified via the file browser.
     */
    sessions: Array<UserScopesOutput.SessionsEnum>;
    /**
     * Create new projects
     */
    projects: Array<UserScopesOutput.ProjectsEnum>;
    /**
     * Manage Personal Access Tokens. Use with caution! This permission can be used to escalate privileges by creating tokens with a larger scope.
     */
    tokens: Array<UserScopesOutput.TokensEnum>;
    /**
     * Submit feedback
     */
    feedback: Array<UserScopesOutput.FeedbackEnum>;
}
export namespace UserScopesOutput {
    export type SessionsEnum = 'GET' | 'CREATE' | 'UPDATE' | 'DELETE';
    export const SessionsEnum = {
        Get: 'GET' as SessionsEnum,
        Create: 'CREATE' as SessionsEnum,
        Update: 'UPDATE' as SessionsEnum,
        Delete: 'DELETE' as SessionsEnum
    };
    export type ProjectsEnum = 'CREATE';
    export const ProjectsEnum = {
        Create: 'CREATE' as ProjectsEnum
    };
    export type TokensEnum = 'GET' | 'CREATE' | 'DELETE';
    export const TokensEnum = {
        Get: 'GET' as TokensEnum,
        Create: 'CREATE' as TokensEnum,
        Delete: 'DELETE' as TokensEnum
    };
    export type FeedbackEnum = 'CREATE';
    export const FeedbackEnum = {
        Create: 'CREATE' as FeedbackEnum
    };
}


