# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

docker:
  registry: k3d-myregistry.localhost:12345
  externalRegistry: docker.io

k8s:
  # Only required when using operator k8s

  context: k3d-collab-cluster # Only required, if you'd like to use a local k3d environment
  namespace: collab-sessions

  # apiURL: dummy # Only required when no kubectl context is available
  # token: dummy # Only required when no kubectl context is available

  storageClassName: local-path
  storageAccessMode: ReadWriteOnce

  cluster:
    imagePullPolicy: Always
    podSecurityContext:
      runAsUser: 1004370000
      runAsGroup: 1004370000
      fsGroup: 1004370000
      runAsNonRoot: true

  promtail:
    lokiEnabled: false
    lokiUrl:
    lokiUsername:
    lokiPassword:
    serverPort:

extensions:
  guacamole:
    baseURI: http://localhost:8080/guacamole
    publicURI: http://localhost:8080/guacamole

    username: guacadmin
    password: guacadmin

authentication:
  provider: oauth # oauth | azure
  jwt:
    usernameClaim: sub # preferred_username

  oauth:
    # Only required when using provider oauth
    endpoints:
      wellKnown: http://localhost:8083/default/.well-known/openid-configuration
      tokenIssuance:
      authorization:

    audience: default

    scopes:
      - openid

    client:
      id: default
      secret:

    redirectURI: http://localhost:4200/oauth2/callback

  # azure:
  #   # Only required when using provider azure
  #   authorizationEndpoint: http://tbd

  #   client:
  #     id: tbd
  #     secret: tbd

  #   audience: tbd
  #   redirectURI: http://localhost:4200/oauth2/callback

database:
  url: postgresql://dev:dev@localhost:5432/dev

initial:
  admin: admin

logging:
  level: DEBUG
  logPath: logs/

requests:
  timeout: 2

prometheus:
  url: http://localhost:8080/prometheus/
