docker: 
  images: 
    workspaces: 
      persistent: k3d-myregistry.localhost:12345/t4c/client/remote
      readonly: k3d-myregistry.localhost:12345/capella/readonly
  
    backup: k3d-myregistry.localhost:12345/t4c/client/importer

operators: 
  operator: k8s # docker | k8s

  docker: 
    ### DEPRECATED. PLEASE CONSIDER SWITCHING TO KUBERNETES ###
    # Only required when using operator docker
    mountVolume: C:/workspaces
    portRange: 50000-50010
    containerHost: host.docker.internal

  k8s: 
    # Only required when using operator k8s

    context: k3d-mycluster # Only required, if you'd like to use a local k3d environment
    namespace: t4c-sessions

    apiURL: # Only required when no kubectl context is available
    token:  # Only required when no kubectl context is available

    storageClassName: local-path

    cluster: 
      containers: 
        # The following values are appended to each container

extensions: 
  guacamole: 
    baseURI: http://localhost:8081/guacamole
    publicURI: http://localhost:8081/guacamole
    
    username: guacadmin
    password: guacadmin

authentication:
  provider: oauth # oauth | azure
  jwt:
    usernameClaim: sub # preferred_username

  oauth: 
    # Only required when using provider oauth
    endpoints: 
      wellKnown: https://localhost:8080/default/.well-known/openid-configuration
      tokenIssuance: 
      authorization: 

    audience: default

    publicKey: |
      

    client: 
      id: 
      secret: 

    redirectURI: http://localhost:4200/oauth2/callback
    

  azure: 
    # Only required when using provider oauth
    authorizationEndpoint: http://tbd
    
    client: 
      id: tbd
      secret: tbd

    audience: tbd
    redirectURI: http://localhost:4200/oauth2/callback
    
    connectConfigurationEndpoint: https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration

modelsources: 
  t4c: 
    usageAPI: http://localhost:8081/mock
    restAPI: http://localhost:8081/mock/api/v1.0

    username: sampleuser
    password: samplepassword

    host: localhost
    port: 2036
    licence: test

backups: 
  enabled: ["importer"]
 
  importer: 
    git: 
      email: bot@example.com

  jenkins: 
    username: 
    password: 
    baseURL: 

    git: 
      credentialID: 
      email: bot@example.com
      scriptRepoURL: 



database: 
  url: postgresql://dev:dev@localhost:5432/dev

initial: 
  admin: your-username

logging: 
  level: DEBUG

requests: 
  timeout: 2