# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

staging:
  rules:
    # For commits on the main branch, build for the staging environment
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual
  variables:
    TARGET: staging
    REVISION: '$CI_COMMIT_REF_NAME'
    DOCKER_BUILD_ARGS: '' # Enable Docker build cache
  trigger:
    project: '$DEPLOYMENT_GITLAB_REPOSITORY'
    strategy: depend

production:
  rules:
    # For tags, build for the production environment
    - if: '$CI_COMMIT_TAG != null'
  variables:
    TARGET: production
    REVISION: '$CI_COMMIT_REF_NAME'
  trigger:
    project: '$DEPLOYMENT_GITLAB_REPOSITORY'
    strategy: depend
