backend:
  authentication: 
    provider: oauth
    jwt:
      usernameClaim: sub

    oauth:
      endpoints: 
        # Endpoint that issues JWT Tokens
        tokenIssuance: https://sso.test.service.deutschebahn.com/f5-oauth2/v1/token
        # Endpoint that authorizes the User
        authorization: https://sso.test.service.deutschebahn.com/f5-oauth2/v1/authorize
        # WellKnown Endpoint
        wellKnown: https://sso.test.service.deutschebahn.com/f5-oauth2/v1/.well-known/openid-configuration

      audience: sub
      scopes: 

      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8YK7mCvxU9+FE8AUpq7
        fbGykv329WQyHzpdp7B+fqvtkLAD3ZRahvsH+mQx+Dy8XcgIRlODqEGk5KBdeOqH
        Q2XVdzqiPg48uP/FecLnKc/sPxgIHiZW1/aEuA+qIj/Z45WutEiKN8gBsB+pgCyW
        vI+gaKTgFs6FRTvYxW2xezaljpX8aDXgQejjwAnH/OL6OZzfsSoOKxGMS9owUphx
        jenE+24pZSCBVZk0pCtJUI06aUAJmqkYA/9+yMujNwVXJGpGeIAnfXg2IZ2fV2Ld
        opjr8p7667gN2DXqUSz8WWzVSVH3DAFEv0U5lhLRFY7dsxK8nDMvpkF7Ij+ICa8M
        sQIDAQAB
        -----END PUBLIC KEY-----

      client: 
        # OAUTH2 Client ID
        id: b58b8659ff0433ed527b8c4ec6b602a0ec57b00cff30f860
        # OAUTH2 Client Secret
        secret: c344e0e2aba3536c79403cf5ca05da89be5b5a7484fb02a0ec57b00cff30f860

      redirectURI: https://dev.t4c.ssi.dbmc.comp.db.de/oauth2/callback