include:
  - project: "se-toolchain/ci-templates-docker"
    ref: v1.0.5
    file:
      - "/gitlab-ci/docker/upload-registry.yml"

stages: 
  - deploy
  - trigger

docker-registry:
  variables:
    DOCKER_IMAGE_NAME: "t4c/client/backend"
  extends: .push-to-registry-using-base-image

trigger-garbage-cleaner:
  only:
    - master
  stage: trigger
  trigger: se-toolchain/t4c-client/t4c-client-garbage-cleaner
