# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

"""Added polarion instance table

Revision ID: 0e7582e0da76
Revises: f55b41e32223
Create Date: 2024-01-30 15:01:27.384061

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e7582e0da76"
down_revision = "f55b41e32223"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "polarion_instances",
        sa.Column("id", sa.Integer()),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String()),
    )
    # ### end Alembic commands ###
