# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

"""Rename indexes for models table

Revision ID: bfd23f119dd4
Revises: 7a3d5e6862a2
Create Date: 2022-09-01 11:09:30.903954

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bfd23f119dd4"
down_revision = "d64fc5a97252"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_capella_models_id", table_name="models")
    op.drop_index("ix_capella_models_name", table_name="models")
    op.create_index(op.f("ix_models_id"), "models", ["id"], unique=False)
    op.create_index(op.f("ix_models_name"), "models", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_models_name"), table_name="models")
    op.drop_index(op.f("ix_models_id"), table_name="models")
    op.create_index("ix_capella_models_name", "models", ["name"], unique=False)
    op.create_index("ix_capella_models_id", "models", ["id"], unique=False)
    # ### end Alembic commands ###
