apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
  labels: 
    id: {{ .Release.Name }}-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.general.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 80
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-nginx-clusterip
                port:
                  number: 80
          - path: /guacamole
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-guacamole-guacamole
                port:
                  number: 8080
