apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: t4c-manager
data:
  prometheus.rules: |-
    {{- toYaml .Values.prometheus.rules | nindent 4 }}
    
  prometheus.yml: |-
    {{- toYaml .Values.prometheus.config | nindent 4 }}