# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-prometheus-nginx
data:
  nginx.conf: |-
    {{ tpl (.Files.Get "config/nginx-prometheus.conf") . | nindent 4 }}
