# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-server
  namespace: t4c-manager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9118"
  labels:
    id: {{ .Release.Name }}-service-prometheus
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-prometheus-server
  ports:
    - port: 9118
      targetPort: 9090
      protocol: TCP
      name: promui
