# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus-nginx
  labels:
    id: {{ .Release.Name }}-deployment-prometheus-nginx
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/prometheus/prometheus-nginx.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.prometheusNginx | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-prometheus-nginx
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-prometheus-nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prometheus/prometheus-nginx.configmap.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: {{ .Release.Name }}-prometheus-nginx
          configMap:
            name: {{ .Release.Name }}-prometheus-nginx
      {{- include "capellacollab.pod.spec" . | indent 6 -}}
      containers:
        - name: {{ .Release.Name }}-prometheus-nginx
          {{- include "capellacollab.container.spec" . | indent 10 -}}
          {{ if .Values.docker.images.nginxUnprivileged }}
          image: {{ .Values.docker.images.nginxUnprivileged }}
          {{ else }}
          image: {{ .Values.docker.registry.external }}/nginxinc/nginx-unprivileged
          {{ end }}
          ports:
            - name: promui
              containerPort: 9118
              protocol: TCP
          resources:
            requests:
              cpu: "1m"
              memory: 5Mi
              ephemeral-storage: '1Gi'
            limits:
              cpu: "2m"
              memory: 20Mi
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: {{ .Release.Name }}-prometheus-nginx
              mountPath: /etc/nginx
