# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus-server
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-deployment-prometheus-server
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/prometheus/prometheus.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.prometheus | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-prometheus-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-prometheus-server
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prometheus/prometheus.configmap.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ .Release.Name }}-prometheus
      {{- include "capellacollab.pod.spec" . | indent 6 -}}
      containers:
        - name: prometheus
          {{- include "capellacollab.container.spec" . | indent 10 -}}
          {{ if .Values.docker.images.prometheus }}
          image: {{ .Values.docker.images.prometheus }}
          {{ else }}
          image: {{ .Values.docker.registry.external }}/prom/prometheus
          {{ end }}
          args:
            - "--storage.tsdb.retention.time=1y"
            - "--storage.tsdb.retention.size=14GB"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.external-url=http://{{ .Release.Name }}-prometheus-server/prometheus/"
          ports:
            - containerPort: 9118
          resources:
            {{ if .Values.development }}
            limits:
              cpu: "0.2"
              memory: 200Mi
              ephemeral-storage: "2Gi"
            requests:
              cpu: "0.05"
              memory: 50Mi
              ephemeral-storage: '1Gi'
            {{ else }}
            limits:
              cpu: 1
              memory: 1Gi
              ephemeral-storage: "2Gi"
            requests:
              cpu: 500m
              memory: 500M
              ephemeral-storage: '1Gi'
            {{ end }}
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-prometheus
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name -}}-prometheus
