# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-nginx
data:
  nginx.conf: |-
    {{ tpl (.Files.Get "config/nginx.conf") . | nindent 4 }}
