# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    id: {{ .Release.Name }}-deployment-nginx
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/routing/nginx.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.routing | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-nginx
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/routing/nginx.configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-nginx
          configMap:
            name: {{ .Release.Name }}-nginx
      {{- include "capellacollab.pod.spec" . | indent 6 -}}
      containers:
        - name: {{ .Release.Name }}-nginx
          image: {{ .Values.docker.registry.external }}/nginxinc/nginx-unprivileged
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{ if .Values.development }}
            limits:
              cpu: "0.1"
              memory: 50Mi
            requests:
              cpu: "0.05"
              memory: 5Mi
            {{ else }}
            limits:
              cpu: "1"
              memory: 100Mi
            requests:
              cpu: "0.25"
              memory: 50Mi
            {{ end }}
          volumeMounts:
            - name: {{ .Release.Name }}-nginx
              mountPath: /etc/nginx
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
