# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    id: {{ .Release.Name }}-nginx
  annotations:
    nginx.ingress.kubernetes.io/fastcgi_buffer_size: 16k
    nginx.ingress.kubernetes.io/fastcgi_buffers: 16 16k
    nginx.ingress.kubernetes.io/fastcgi_busy_buffers_size: 16k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"
    {{- if eq .Values.cluster.kind "OpenShift" }}
    route.openshift.io/insecureEdgeTerminationPolicy: Redirect
    route.openshift.io/termination: edge
    {{ end }}
spec:
  ingressClassName: {{ .Values.cluster.ingressClassName }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 80
          - &backend_rule
            path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  name: http
          - <<: *backend_rule
            path: /metrics
          - <<: *backend_rule
            path: /docs/api/swagger
          - <<: *backend_rule
            path: /docs/api/openapi.json
          - <<: *backend_rule
            path: /docs/api/redoc
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-docs
                port:
                  number: 80
          - path: /guacamole
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-guacamole-guacamole
                port:
                  number: 8080
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-prometheus-nginx
                port:
                  name: promui
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-grafana-nginx
                port:
                  name: grafui
          {{ if .Values.mocks.oauth }}
          - path: /default
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-oauth-mock
                port:
                  number: 8080
          {{ end }}
          {{ if .Values.mocks.smtp }}
          - path: /smtp
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-smtp-mock
                port:
                  number: 8080
          {{ end }}
      {{ if not .Values.general.wildcardHost }}
      host: {{ .Values.general.host }}
      {{ end }}
