# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.database.backend.deploy }}
{{ if not .Values.development }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-volume-backend-postgres
  labels:
    id: {{ .Release.Name }}-pvc-backend-postgres
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.cluster.pvc.storageClassName }}
{{ end }}
{{ end }}
