# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-serviceaccount-backend
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: {{ .Values.backend.k8sSessionNamespace }}
 name: {{ .Release.Name }}-backend
 labels:
    id: {{ .Release.Name }}-role-backend
rules:
- apiGroups:
    - "apps"
  resources:
    - "deployments"
  verbs:
    - get
    - create
    - delete
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - get
    - create
    - delete
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - get
    - create
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - create
    - delete
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
    - events
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods/exec
  verbs:
    - get
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.backend.k8sSessionNamespace }}
  labels:
    id: {{ .Release.Name }}-rolebinding-backend
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-backend
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-backend
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-promtail-backend
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-role-promtail-backend
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-promtail-backend
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-rolebinding-promtail-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-promtail-backend
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: {{ .Release.Name }}-backend
    namespace: {{ .Release.Namespace }}
