# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    id: {{ .Release.Name }}-deployment-backend
  annotations:
    checksum/config-backend: {{ include (print $.Template.BasePath "/backend/backend.configmap.yaml") . | sha256sum }}
    checksum/config-promtail: {{ include (print $.Template.BasePath "/promtail" "/promtail.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.backend | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-backend
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-backend
      annotations:
        checksum/config-backend: {{ include (print $.Template.BasePath "/backend/backend.configmap.yaml") . | sha256sum }}
        checksum/config-promtail: {{ include (print $.Template.BasePath "/promtail" "/promtail.configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-backend
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-backend
        {{ if .Values.loki.enabled }}
        - name: logs
          emptyDir: {}
        - name: prom-config
          configMap:
            name: {{ .Release.Name }}-promtail
            items:
              - key: backend-promtail.yaml
                path: promtail.yaml
        - name: prom-position
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-backend-promtail
        {{ end }}
      {{- include "capellacollab.pod.spec" . | indent 6 -}}
      containers:
        - name: {{ .Release.Name }}-backend
          image: {{ .Values.docker.registry.internal }}{{ .Values.docker.images.backend }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
          {{ if .Values.mocks.oauth }}
            - name: OAUTHLIB_INSECURE_TRANSPORT
              value: "1"
          {{ end }}
            - name: DEVELOPMENT_MODE
              value: "{{ .Values.development }}"
            - name: no_proxy_additional
              value: "{{ .Values.proxy.no_proxy }}"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          resources:
            {{ if .Values.development }}
            limits:
              cpu: "0.25"
              memory: 150Mi
            requests:
              cpu: "0.06"
              memory: 20Mi
            {{ else }}
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: "0.25"
              memory: 20Mi
            {{ end }}
          volumeMounts:
            - name: config
              mountPath: /etc/capellacollab
              readOnly: true
            {{ if .Values.loki.enabled }}
            - name: logs
              mountPath: /var/log/backend
            {{ end }}
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
        {{ if .Values.loki.enabled }}
        - name: promtail
          image: {{ .Values.docker.registry.external -}}/grafana/promtail
          args:
            - "--config.file=/etc/promtail/promtail.yaml"
            - "-log-config-reverse-order"
          ports:
            - name: logs
              containerPort: 3101
              protocol: TCP
          resources:
            {{ if .Values.development }}
            limits:
              cpu: "0.1"
              memory: 50Mi
            requests:
              cpu: "0.02"
              memory: 5Mi
            {{ else }}
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.2"
              memory: 250Mi
            {{ end }}
          volumeMounts:
            - name: prom-config
              mountPath: /etc/promtail
            - name: prom-position
              mountPath: /var/log/promtail
            - name: logs
              readOnly: true
              mountPath: /var/log/backend
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
        {{ end }}
