# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-serviceaccount-backend
{{- if .Values.cluster.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.cluster.imagePullSecret }}
{{ end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: {{ .Values.backend.k8sSessionNamespace }}
 name: {{ .Release.Name }}-backend
 labels:
    id: {{ .Release.Name }}-role-backend
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "events"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["create", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.backend.k8sSessionNamespace }}
  labels:
    id: {{ .Release.Name }}-rolebinding-backend
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-backend
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-backend
  apiGroup: rbac.authorization.k8s.io
