# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-backend
data:
  config.yaml: |
    {{- tpl (.Files.Get "config/backend.yaml") . | nindent 4 }}
