apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels: 
    id: {{ .Release.Name }}-configmap-backend
data:
  config.yaml: |
    {{- tpl (.Files.Get "config/backend.yaml") . | nindent 4 }}
  {{ if eq .Values.target "local" }}
  oauth.crt: |-
    {{ .Files.Get "config/oauth.crt" | nindent 4 }}
  {{ end }}