# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels: 
    id: {{ .Release.Name }}-deployment-backend
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/backend/backend.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector: 
    matchLabels: 
      id: {{ .Release.Name }}-deployment-backend
  template:
    metadata: 
      labels: 
        id: {{ .Release.Name }}-deployment-backend
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount-backend
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-backend
      containers:
        - name: {{ .Release.Name }}-backend
          image: {{ .Values.docker.registry.internal }}{{ .Values.docker.images.backend }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{ if eq .Values.target "local" }}
          env:
            - name: OAUTHLIB_INSECURE_TRANSPORT
              value: "1"
          {{ end }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
          readinessProbe: 
            httpGet:
              path: /healthcheck
              port: http
          resources:
            limits:
              cpu: "1"
              memory: 200Mi
            requests:
              cpu: "0.25"
              memory: 20Mi
          volumeMounts:
            - name: config
              mountPath: /etc/capellacollab
              readOnly: true
          {{ if .Values.cluster.container }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}