# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-{{- .Values.backend.k8sSessionNamespace -}}-to-backend
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-backend
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.backend.k8sSessionNamespace }}
  policyTypes:
    - Ingress
