apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels: 
    id: {{ .Release.Name }}-deployment-backend
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/backend/backend.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector: 
    matchLabels: 
      id: {{ .Release.Name }}-deployment-backend
  template:
    metadata: 
      labels: 
        id: {{ .Release.Name }}-deployment-backend
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount-backend
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-backend
      containers:
        - name: {{ .Release.Name }}-backend
          image: {{ .Values.docker.registry.internal }}{{ .Values.docker.images.backend }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe: 
            httpGet:
              path: /healthcheck
              port: http
          resources:
            limits:
              cpu: "1"
              memory: 200Mi
            requests:
              cpu: "0.25"
              memory: 20Mi
          volumeMounts:
            - name: config
              mountPath: "/root/.config/capellacollab/config.yaml"
              readOnly: true
          {{ if .Values.cluster.container }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}