# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

{{- /* 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-garbage-cleaner
  annotations:
    checksum/config_env: {{ include (print $.Template.BasePath "/backend/backend_env.configmap.yaml") . | sha256sum }}
spec:
  schedule: "{{ .Values.backend.garbageCleaner.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "OnFailure"
          containers: 
            - name: {{ .Release.Name }}-garbage-cleaner
              image: {{ .Values.docker.registry.internal }}{{ .Values.docker.images.backend }}
              command: ["python3"]
              args: ["-m", "t4cclient.core.garbage_cleaner"]
              envFrom:
                - configMapRef: 
                    name: {{ .Release.Name }}-backend-env
              resources: 
                limits:
                  cpu: "0.5"
                  memory: 100Mi
                requests:
                  cpu: "0.25"
                  memory: 10Mi
              {{ if .Values.cluster.containers }}
              {{- toYaml .Values.cluster.containers | nindent 10 }}
              {{ end }}
*/}}