# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.database.backend.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-postgres
  labels:
    id: {{ .Release.Name }}-service-backend-postgres
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-backend-postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
{{ end }}
