{{ if .Values.database.backend.deploy }}
{{ if ne .Values.target "local" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-volume-backend-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.database.backend.internal.storageClassName }}
{{ end }}
{{ end }}