# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-redis
  labels:
    id: {{ .Release.Name }}-service-backend-redis
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-backend-redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
