# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docs
  labels:
    id: {{ .Release.Name }}-service-docs
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-docs
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
