apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-serviceaccount-backend
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: {{ .Values.k8sSessionNamespace }}
 name: {{ .Release.Name }}-role-backend
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding-backend
  namespace: {{ .Values.k8sSessionNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-serviceaccount-backend
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role-backend
  apiGroup: rbac.authorization.k8s.io
