# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

# Expose Grafana Loki API on development systems for direct access

{{ if .Values.development }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loki-nodeport
  labels:
    id: {{ .Release.Name }}-service-loki-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: loki
  ports:
  - name: http
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: http
{{ end }}
