# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

{{ if eq .Values.target "local" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mock-clusterip
  labels:
    id: {{ .Release.Name }}-service-mock-clusterip
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-mock-nginx
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
{{ end }}
