# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.mocks.oauth }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oauth-mock
  labels:
    id: {{ .Release.Name }}-service-oauth-mock
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-oauth-mock
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
{{ end }}
