# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.mocks.smtp }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-smtp-mock
  labels:
    id: {{ .Release.Name }}-deployment-smtp-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-smtp-mock
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-smtp-mock
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Release.Name }}-smtp-mock
          {{ if .Values.docker.images.smtp4dev }}
          image: {{ .Values.docker.images.smtp4dev }}
          {{ else }}
          image: {{ .Values.docker.registry.external }}/rnwood/smtp4dev
          {{ end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: smtp
              containerPort: 25
              protocol: TCP
          env:
            - name: ServerOptions__TlsMode
              value: StartTls
            - name: ServerOptions__BasePath
              value: /smtp
            - name: ServerOptions__Urls
              value: "{{ .Values.general.scheme }}://{{ .Values.general.host }}:{{ .Values.general.port }}"
          resources:
            limits:
              cpu: "0.2"
              memory: 0.2Gi
            requests:
              cpu: "0.1"
              memory: 50Mi
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
{{ end }}
