{
 "title": "Active sessions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tool_version_id",
    "label": "Tool and Version",
    "query": {
     "query": "up{job=\"sessions\"}"
    }
   },
   {
    "name": "connection_method_id",
    "label": "Connection Method",
    "query": {
     "query": "up{job=\"sessions\", tool_version_id=~\"$tool_version_id\"}"
    }
   },
   {
    "name": "session_type",
    "label": "Session Type",
    "query": {
     "query": "label_values(up{job=\"sessions\", tool_version_id=~\"$tool_version_id\"},session_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count(up{tool_version_id=~\"$tool_version_id\",connection_method_id=~\"$connection_method_id\", session_type=~\"$session_type\", job=\"sessions\"})) OR on() vector(0)",
     "legendFormat": "Number of sessions"
    },
    {
     "expr": "(count(up{tool_version_id=~\"$tool_version_id\",connection_method_id=~\"$connection_method_id\", session_type=~\"$session_type\", job=\"sessions\"} == 0)) OR vector(0)",
     "legendFormat": "Sessions with scraping errors"
    }
   ]
  },
  {
   "title": "Active sessions per tool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count by (tool_id, tool_name) (up{tool_version_id=~\"$tool_version_id\",connection_method_id=~\"$connection_method_id\", session_type=~\"$session_type\", job=\"sessions\"})",
     "legendFormat": "{{tool_name}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(up{tool_version_id=~\"$tool_version_id\",connection_method_id=~\"$connection_method_id\", session_type=~\"$session_type\", job=\"sessions\"})) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session idletimes",
   "type": "timeseries",
   "description": "How long sessions were idle. When a session reaches the top of the graph, it is terminated automatically.",
   "gridPos": { "h": 6, "w": 14, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "idletime_minutes{tool_version_id=~\"$tool_version_id\",connection_method_id=~\"$connection_method_id\", session_type=~\"$session_type\"}",
     "legendFormat": "{{session_id}} ({{tool_name}} {{tool_version_name}} with {{connection_method_name}})"
    }
   ]
  }
 ]
}