{
 "title": "Feedback",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Feedback Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(sum by (rating) (increase(feedback_count[$__range])))",
     "legendFormat": "{{rating}}"
    }
   ]
  },
  {
   "title": "Feedback",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (rating) (increase(feedback_count[$__range])))",
     "legendFormat": "{{rating}}"
    }
   ]
  },
  {
   "title": "User Happiness Index",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(feedback_count{rating=\"good\"}[$__range]) * 10) + sum(increase(feedback_count{rating=\"okay\"}[$__range]) * 5)) / sum(increase(feedback_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Share of anonymous feedback",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((sum(increase(feedback_count{anonymous=\"true\"}[$__range])) / (sum(increase(feedback_count[$__range])) - (sum(increase(feedback_count{anonymous=\"\"}[$__range])) or vector(0)))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Happiness Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(sum(increase(feedback_count{rating=\"good\"}[$__range]) * 10) + sum(increase(feedback_count{rating=\"okay\"}[$__range]) * 5)) / sum(increase(feedback_count[$__range]))",
     "legendFormat": "User happiness index"
    }
   ]
  }
 ]
}