{
 "title": "Individual Session",
 "description": "Have a deeper look at a specific session",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "session_id",
    "label": "Session ID",
    "query": {
     "query": "label_values(idletime_minutes,session_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tool + Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{session_id=~\"$session_id\"}",
     "legendFormat": "{{tool_name}} {{tool_version_name}}"
    }
   ]
  },
  {
   "title": "Connection Method",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{session_id=~\"$session_id\"}",
     "legendFormat": "{{connection_method_name}}"
    }
   ]
  },
  {
   "title": "Session Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{session_id=~\"$session_id\"}",
     "legendFormat": "{{session_type}}"
    }
   ]
  },
  {
   "title": "Scraping errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(up{session_id=~\"$session_id\"} == 0)) OR vector(0)",
     "legendFormat": "Sessions with scraping errors"
    }
   ]
  },
  {
   "title": "Session Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "xpra_client_encoding_quality{session_id=~\"$session_id\", type=\"cur\"}",
     "legendFormat": "Xpra encoding quality"
    }
   ]
  },
  {
   "title": "Process threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "process_num_threads{session_id=~\"$session_id\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Session idletime",
   "type": "timeseries",
   "description": "How long the session was idle. When a session reaches the top of the graph, it is terminated automatically.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "idletime_minutes{session_id=~\"$session_id\"}",
     "legendFormat": "The session has been idle for"
    }
   ]
  },
  {
   "title": "Session duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(up{session_id=~\"$session_id\"}[$__range])/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{session_id=~\"$session_id\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Session Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "xpra_client_batch_delay_ms{session_id=~\"$session_id\", type=\"cur\"}",
     "legendFormat": "Batch delay"
    },
    {
     "expr": "xpra_client_damage_in_latency_ms{session_id=~\"$session_id\", type=\"cur\"}",
     "legendFormat": "Damage request latency"
    },
    {
     "expr": "xpra_client_jitter_ms{session_id=~\"$session_id\"}",
     "legendFormat": "Jitter"
    },
    {
     "expr": "xpra_client_latency_ms{session_id=~\"$session_id\"}",
     "legendFormat": "Client latency"
    },
    {
     "expr": "xpra_connection_client_ping_latency_ms{session_id=~\"$session_id\", type=\"cur\"}",
     "legendFormat": "Ping latency"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_percent{session_id=~\"$session_id\"}",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Session Logs",
   "type": "logs",
   "description": "The oldest logs are displayed first.",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{session_id=\"$session_id\"} |= ``"
    }
   ]
  },
  {
   "title": "I/O Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_io_counters_bytes{session_id=~\"$session_id\"}",
     "legendFormat": "{{process_name}} ({{io_type}})"
    }
   ]
  }
 ]
}