{
 "title": "Management Portal Logs",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Backend Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployment=~\".*-deployment-backend\"} |= `` | logfmt | level = `ERROR`"
    }
   ]
  },
  {
   "title": "Frontend Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployment=~\".*-deployment-frontend\"} |= ``"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployment=~\".*-deployment-backend\"} |= `` | logfmt"
    }
   ]
  }
 ]
}