{
 "title": "Users",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Registered Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (user_count)",
     "legendFormat": "Registered Users"
    },
    {
     "expr": "user_count{beta=\"true\"}",
     "legendFormat": "Beta Testers"
    }
   ]
  },
  {
   "title": "Share of Beta Testers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(user_count{beta=\"true\"} / scalar(sum(user_count{}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beta Program Joiners",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(user_count{beta=\"true\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beta Program Leavers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(user_count{beta=\"true\"}[$__range]) - delta(user_count{beta=\"true\"}[$__range])) * -1\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}