# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
