# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-backend-valkey
spec:
  minAvailable: 1
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-valkey
