# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-valkey
  labels:
    id: {{ .Release.Name }}-secret-valkey
type: Opaque
stringData:
  valkey.conf: |
    requirepass {{ .Values.valkey.password | required ".Values.valkey.password is required. Please generate a random password and set it in the values.yaml." }}
