# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-valkey
  labels:
    id: {{ .Release.Name }}-deployment-valkey
spec:
  replicas: {{ .Values.replicaCount.valkey | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-valkey
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-valkey
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          secret:
            secretName: {{ .Release.Name }}-valkey
      containers:
        - name: {{ .Release.Name }}-valkey
          {{ if .Values.docker.images.valkey }}
          image: {{ .Values.docker.images.valkey }}
          {{ else }}
          image: {{ .Values.docker.registry.external }}/valkey/valkey:7.2.6
          {{ end }}
          args: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
          ports:
            - name: valkey
              containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: "25m"
              memory: 25Mi
              ephemeral-storage: '1Gi'
            limits:
              cpu: "25m"
              memory: 500Mi
              ephemeral-storage: "5Gi"
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /usr/local/etc/valkey/valkey.conf
              name: config
              subPath: valkey.conf
