
# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if and .Values.database.guacamole.deploy .Values.guacamole.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-guacamole-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    id: {{ .Release.Name }}-configmap-guacamole-postgres
data:
  initdb.sql: |-
    {{ .Files.Get "config/initdb.sql" | nindent 4 }}
{{ end }}
