# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if and .Values.database.guacamole.deploy .Values.guacamole.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-volume-guacamole-postgres
  labels:
    id: {{ .Release.Name }}-pvc-guacamole-postgres
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.cluster.pvc.storageClassName }}
{{ end }}
