# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-guacamole-guacamole
  labels:
    id: {{ .Release.Name }}-deployment-guacamole-guacamole
  annotations:
    checksum/config-promtail: {{ include (print $.Template.BasePath "/promtail" "/promtail.configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount.guacamole | default 1 }}
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-guacamole-guacamole
  template:
    metadata:
      labels:
        id: {{ .Release.Name }}-deployment-guacamole-guacamole
      annotations:
        checksum/config-promtail: {{ include (print $.Template.BasePath "/promtail" "/promtail.configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        {{ if .Values.loki.enabled }}
        - name: unused
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: prom-config
          configMap:
            name: {{ .Release.Name }}-promtail
            items:
              - key: guacamole-promtail.yaml
                path: promtail.yaml
        - name: prom-position
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-guacamole-promtail
        {{ end }}
      {{- include "capellacollab.pod.spec" . | indent 6 -}}
      containers:
        - name: {{ .Release.Name }}-guacamole-guacamole
          image: {{ .Values.docker.images.guacamole.guacamole }}
          env:
            - name: GUACD_HOSTNAME
              value: {{ .Release.Name }}-guacamole-guacd
          {{ if .Values.database.guacamole.deploy }}
            - name: POSTGRES_DATABASE
              value: "guacamole"
            - name: POSTGRES_HOSTNAME
              value: {{ .Release.Name }}-guacamole-postgres
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.guacamole.internal.password }}
            - name: POSTGRES_USER
              value: guacamole
          {{ else }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.database.guacamole.external.database }}
            - name: POSTGRES_HOSTNAME
              value: {{ .Values.database.guacamole.external.hostname }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.guacamole.external.password }}
            - name: POSTGRES_USER
              value: {{ .Values.database.guacamole.external.username }}
            - name: POSTGRESQL_SSL_MODE
              value: require
          {{ end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            {{ if .Values.loki.enabled }}
            # https://github.com/kubernetes/kubernetes/issues/106194
            - name: unused
              mountPath: /home/guacamole/tomcat
            - name: logs
              mountPath: /home/guacamole/tomcat/logs
            {{ end }}
          resources:
            {{ if eq .Values.target "local" }}
            requests:
              cpu: "0.1"
              memory: 20Mi
            limits:
              cpu: "1"
              memory: 1Gi
            {{ else }}
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
            {{ end }}
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
        {{ if .Values.loki.enabled }}
        - name: promtail
          image: {{ .Values.docker.registry.external -}}{{- .Values.docker.images.promtail }}
          args:
            - "--config.file=/etc/promtail/promtail.yaml"
            - "-log-config-reverse-order"
          ports:
            - name: logs
              containerPort: 3101
              protocol: TCP
          resources:
            {{ if eq .Values.target "local" }}
            limits:
              cpu: "0.1"
              memory: 50Mi
            requests:
              cpu: "0.02"
              memory: 5Mi
            {{ else }}
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.2"
              memory: 250Mi
            {{ end }}
          volumeMounts:
            - name: prom-config
              mountPath: /etc/promtail
            - name: prom-position
              mountPath: /var/log/promtail
            - name: logs
              mountPath: /var/log/guacamole
          {{ if .Values.cluster.containers }}
          {{- toYaml .Values.cluster.containers | nindent 10 }}
          {{ end }}
        {{ end }}
