# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guacamole-guacamole
  labels:
    id: {{ .Release.Name }}-service-guacamole-guacamole
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-guacamole-guacamole
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
