# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.guacamole.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-guacamole-guacd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      id: {{ .Release.Name }}-deployment-guacamole-guacd
{{ end }}
