apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guacamole-guacd
  labels: 
    id: {{ .Release.Name }}-service-guacamole-guacd
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-guacamole-guacd
  ports:
    - port: 4822
      targetPort: guacd
      protocol: TCP
      name: guacd
