
{{ if .Values.database.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-guacamole-postgres
  namespace: {{ .Release.Namespace }}
  labels: 
    id: {{ .Release.Name }}-configmap-guacamole-postgres
data:
  initdb.sql: |- 
    {{ .Files.Get "config/initdb.sql" | nindent 4 }}
{{ end }}

