# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.database.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guacamole-postgres
  labels: 
    id: {{ .Release.Name }}-service-guacamole-postgres
spec:
  type: ClusterIP
  selector:
    id: {{ .Release.Name }}-deployment-guacamole-postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
{{ end }}