
# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.database.guacamole.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-guacamole-postgres
  namespace: {{ .Release.Namespace }}
  labels: 
    id: {{ .Release.Name }}-configmap-guacamole-postgres
data:
  initdb.sql: |- 
    {{ .Files.Get "config/initdb.sql" | nindent 4 }}
{{ end }}

