# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
printWidth: 79
proseWrap: always
