# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0

install:
	python -m venv .venv
	.venv/bin/pip install -r requirements.txt

serve:
	.venv/bin/mkdocs serve
