# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

install:
	python -m venv .venv
	.venv/bin/pip install -r requirements.txt

serve:
	.venv/bin/mkdocs serve
