# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

site_name: Capella Collaboration Manager Documentation
theme:
  name: material
  font: false
  custom_dir: custom_theme/
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs

watch:
  - custom_theme/

extra_css:
  - style.css

nav:
  - General:
      - Introduction: index.md
      - Release Notes: release-notes.md
  - User documentation:
      - Introduction: user/index.md
      - Projects:
          - Get Access to a Project: user/projects/access.md
          - Add a User to a Project: user/projects/add-user.md
          - Request a New Project: user/projects/create.md
          - Roles: user/projects/roles.md
          - Models:
              - Create a Model: user/projects/models/create.md
              - Update Model Metadata: user/projects/models/metadata.md
              - Backups:
                  - Setup a Model Backup: user/projects/models/backups/setup.md
                  - Trigger a Model Backup: user/projects/models/backups/trigger.md
                  - Remove a Model Backup: user/projects/models/backups/remove.md
              - Diagram cache:
                  - Setup Diagram Cache: user/projects/models/diagrams/setup_diagram_cache.md
                  - View Diagram Cache: user/projects/models/diagrams/view_diagram_cache.md
              - Model Complexity Badge: user/projects/models/complexity_badge.md
      - Sessions:
          - Session Types:
              - Overview: user/sessions/types.md
              - Persistent: user/sessions/types/persistent.md
              - Read-Only: user/sessions/types/read-only.md
          - Request Session: user/sessions/request.md
          - (Re-)Connect to Session: user/sessions/reconnect.md
          - Terminate Session: user/sessions/terminate.md
          - Taking Screenshots: user/sessions/screenshot/screenshots.md
          - Files Browser: user/sessions/files/files.md
          - Troubleshooting: user/sessions/troubleshooting.md
      - Capella:
          - Introduction: user/tools/capella/introduction.md
          - Update a Capella Model to a Newer Version: user/tools/capella/migration/update.md
          - Co-working Methods: user/tools/capella/t4c-git-compare.md
          - TeamForCapella:
              - Connect to a TeamForCapella Repository: user/tools/capella/teamforcapella/connect/connect-to-t4c.md
              - Import a Model from TeamForCapella: user/tools/capella/teamforcapella/import/import-from-t4c.md
              - Export a Model to TeamForCapella: user/tools/capella/teamforcapella/export/export-to-t4c.md
          - Git:
              - Working with Git: user/tools/capella/git/working-with-git.md
          - Troubleshooting: user/tools/capella/troubleshooting/index.md
      - Jupyter:
          - Collaboration: user/sessions/jupyter/collaboration.md
  - API documentation:
      - Introduction: api/index.md
      - api/swagger.md
      - api/redoc.md
      - api/openapi.md
  - Administrator Documentation:
      - Introduction: admin/index.md
      - Installation: admin/installation.md
      - Uninstallation: admin/uninstallation.md
      - Getting started: admin/getting_started/getting_started.md
      - Integrations:
          - Git: admin/settings/model-sources/git.md
          - TeamForCapella:
              - Manage T4C Instances: admin/settings/model-sources/t4c.md
              - Full Setup & Integration of a TeamForCapella Project: admin/teamforcapella/full-setup/full-setup.md
              - TeamForCapella Repository Management: admin/teamforcapella/repository-management/repository-management.md
              - TeamForCapella Project Management: admin/teamforcapella/project-management/project-management.md
              - Link a TeamForCapella Repository: admin/teamforcapella/project-integration/project-integration.md
              - Update a TeamForCapella-based Model: admin/teamforcapella/migration/update.md
          - pure::variants: admin/settings/tools/pure_variants.md
      - Tools:
          - General: admin/settings/tools/index.md
          - Configuration: admin/tools/configuration.md
      - Alerts: admin/alerts/create.md
      - Monitoring: admin/settings/monitoring.md
      - CI templates:
          - Gitlab CI/CD:
              - Image builder: admin/ci-templates/gitlab/image-builder.md
              - Kubernetes deployment: admin/ci-templates/gitlab/k8s-deploy.md
      - Command line tool: admin/cli.md
  - Developer Documentation:
      - Introduction: development/index.md
      - Backend:
          - Code Style: development/backend/code-style.md
          - Technology Overview: development/backend/technology.md
          - Extension Modules: development/backend/extensions.md
          - Exception Handling: development/backend/exception.md
          - API Authentication: development/backend/authentication.md
          - Database Migration: development/backend/database-migration.md
      - Frontend:
          - Code Style: development/frontend/code-style.md
          - Responsive Design: development/frontend/responsive-design/mobile-view.md
          - Routes: development/frontend/routes.md
          - Testing: development/frontend/testing.md
          - Customization: development/frontend/customize.md
      - Kubernetes:
          - Measure Resource Usage: development/k8s/resources.md
      - Documentation: development/docs.md

repo_url: https://github.com/DSD-DBS/capella-collab-manager
edit_uri: edit/master/docs/docs

plugins:
  - search
  - redirects:
      redirect_maps:
        'user/sessions/flows/t4c.md': 'user/tools/capella/teamforcapella/connect/connect-to-t4c.md' # The flows section was removed
        'user/sessions/flows/git.md': 'user/tools/capella/git/working-with-git.md' # The flows section was removed
        'user/tokens.md': 'api/index.md' # Authentication information was moved to API documentation
        'user/tools/capella/update.md': 'user/tools/capella/migration/update.md' # A new subdirectory was added
        'user/tools/capella/teamforcapella/repository-management.md': 'admin/teamforcapella/repository-management/repository-management.md' # Moved to admin documentation
        'user/tools/capella/teamforcapella/project-management/project-management.md': 'admin/teamforcapella/project-management/project-management.md' # Moved to admin documentation
        'user/tools/capella/teamforcapella/update.md': 'admin/teamforcapella/migration/update.md' # Moved to admin documentation
        'user/tools/capella/working-with-git.md': 'user/tools/capella/git/working-with-git.md' # A new subdirectory was added

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - abbr
  - pymdownx.snippets
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false

dev_addr: 127.0.0.1:8081

copyright: Copyright &copy; 2022-2024 DB InfraGO AG
