# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1
groups:
  - orgId: 1
    name: Deployment
    folder: Alerts
    interval: 1m
    rules:
      - uid: a32cdf13-990a-438e-a451-11f9185e97b2
        title: Session container unhealthy
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 3600
              to: 0
            datasourceUid: prometheus_ccm
            model:
              datasource:
                type: prometheus
                uid: prometheus_ccm
              editorMode: code
              expr:
                sum by(namespace, pod, phase,
                annotation_capellacollab_session_id)
                (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"} * on
                (uid) group_left kube_pod_labels{label_workload="session"} * on
                (uid) group_left (annotation_capellacollab_session_id)
                kube_pod_annotations) > 0
              instant: true
              intervalMs: 1000
              legendFormat: '{{deployment}}'
              maxDataPoints: 43200
              range: false
              refId: A
        noDataState: OK
        execErrState: OK
        for: 10m
        annotations:
          description: A session container is in an unexpected state.
          runbook_url: ''
          summary:
            Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not
            ready for over 10 minutes.
        labels:
          '': ''
        isPaused: false
      - uid: d7609318-1289-443a-908c-bada900079cc
        title: Job has failed
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 86400
              to: 0
            datasourceUid: prometheus_ccm
            model:
              datasource:
                type: prometheus
                uid: prometheus_ccm
              editorMode: builder
              expr: kube_job_status_failed > 0
              hide: false
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              range: false
              refId: A
        noDataState: OK
        execErrState: OK
        for: 5m
        annotations:
          summary: A job has failed
        isPaused: false
