# Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: Apache-2.0
docker:
  images:
    workspaces:
      persistent: /t4c/client/remote
      readonly: /capella/readonly

    backup: "{{ .Values.docker.registry.internal }}{{ .Values.docker.images.importer }}"


operators:
  operator: k8s

  k8s:
    namespace: {{ .Values.backend.k8sSessionNamespace }}
    storageClassName: {{ .Values.backend.storageClassName }}
    storageAccessMode: {{ .Values.backend.storageAccessMode }}

    cluster:
      containers:
        {{- toYaml .Values.cluster.namespaces.sessions.containers | nindent 8 }}

extensions:
  guacamole:
    baseURI: "http://{{ .Release.Name }}-guacamole-guacamole:8080/guacamole"
    publicURI: "{{ .Values.general.scheme }}://{{ .Values.general.host }}:{{ .Values.general.port }}/guacamole"

    username: guacadmin
    password: guacadmin

authentication:
  provider: "{{ .Values.backend.authentication.provider }}"
  jwt:
    usernameClaim: "{{ .Values.backend.authentication.jwt.usernameClaim }}"

  oauth:
    # Only required when using provider oauth
    endpoints:
      tokenIssuance: "{{ .Values.backend.authentication.oauth.endpoints.tokenIssuance }}"
      authorization: "{{ .Values.backend.authentication.oauth.endpoints.authorization }}"
      wellKnown: "{{ .Values.backend.authentication.oauth.endpoints.wellKnown }}"

    audience: "{{ .Values.backend.authentication.oauth.audience }}"

    publicKey: |
      {{- .Values.backend.authentication.oauth.publicKey | nindent 6}}

    scopes:
      {{- toYaml .Values.backend.authentication.oauth.scopes | nindent 6}}

    client:
      id: "{{ .Values.backend.authentication.oauth.client.id }}"
      secret: "{{ .Values.backend.authentication.oauth.client.secret }}"

    redirectURI: "{{ .Values.backend.authentication.oauth.redirectURI }}"

  azure:
    # Only required when using provider oauth
    authorizationEndpoint: "{{ .Values.backend.authentication.azure.authorizationEndpoint }}"

    client:
      id: "{{ .Values.backend.authentication.azure.client.id }}"
      secret: "{{ .Values.backend.authentication.azure.client.secret }}"

    redirectURI: "{{ .Values.backend.authentication.azure.redirectURI }}"

    connectConfigurationEndpoint: "{{ .Values.backend.authentication.azure.connectConfigurationEndpoint }}"

modelsources:
  t4c:
    usageAPI: http://localhost:8086
    restAPI: http://localhost:8090/api/v1.0

    username: sampleUser
    password: samplePassword

    host: localhost
    port: 2036
    licenseKey: tbd

backups:
  enabled: ["importer"]

  importer:
    git:
      email: tbd

  jenkins:
    username: tbd
    password: tbd
    baseURL: tbd

    git:
      credentialID: tbd
      email: tbd
      scriptRepoURL: tbd

prometheus:
  url: "http://{{ .Release.Name }}-prometheus-server:9118/prometheus/"

database:
  {{ if .Values.database.backend.deploy }}
  url: "postgresql://backend:{{ .Values.database.backend.internal.password }}@{{ .Release.Name }}-backend-postgres:5432/backend"
  {{ else }}
  url: "{{ .Values.database.backend.external.uri }}"
  {{ end }}


initial:
  admin: "{{ .Values.database.backend.initialAdmin }}"

logging:
  level: DEBUG

requests:
  timeout: 2